# Generated by Django 5.1.3 on 2024-11-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
