# Generated by Django 5.1.3 on 2024-11-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='consultas_usuario',
        ),
    ]
